import { createActionTypes } from "@utils/";

export const ACTION_TYPES = ["FETCH_TODOS", "FETCH_TODO", "ADD_TODO", "EDIT_TODO", "REMOVE_TODO"];
export const todosActionTypes = createActionTypes(ACTION_TYPES);

// const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
// const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
// const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';

// const FETCH_TODO_REQUEST = 'FETCH_TODO_REQUEST';
// const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS';
// const FETCH_TODO_FAILURE = 'FETCH_TODO_FAILURE';

// const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
// const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
// const ADD_TODO_FAILURE = 'ADD_TODO_FAILURE';

// const EDIT_TODO_REQUEST = 'EDIT_TODO_REQUEST';
// const EDIT_TODO_SUCCESS = 'EDIT_TODO_SUCCESS';
// const EDIT_TODO_FAILURE = 'EDIT_TODO_FAILURE';

// const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
// const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
// const REMOVE_TODO_FAILURE = 'REMOVE_TODO_FAILURE';
